# 스터디 멤버 목록
# GitHub username으로 등록
members:
  - username: dev-jiseok
    name: "이지석"
    joined: "2026-03-17"
  - username: seoyoungleeme
    name: "이서영"
    joined: "2026-03-19"
  - username: do-dop
    name: "박도연"
    joined: "2026-03-19"
  - username: wsxchoi
    name: "최우성"
    joined: "2026-03-19"
  - username: Pokingteemo
    name: "정윤섭"
    joined: "2026-03-19"
  - username: seoyeon0201
    name: "박서연"
    joined: "2026-03-19"
  - username: jud1thDev
    name: "정유정"
    joined: "2026-03-19"
  - username: m1cks
    name: "인승진"
    joined: "2026-03-19"
